### ISSUE TITLE
what if ios version below to 10.3

### ISSUE THREAD

**Issue by mike623** [oblador/react-native-store-review#1]
excellent lib! just want to know if there backward solution for below 10.3

**Comment by superandrew213** [comment]
You can use this https://github.com/jlyman/react-native-rating-requestor.

It would be nice if we could track positive events like `react-native-rating-requestor` does to determine when to request reviews.

**Comment by oblador** [comment]
What I do in my apps is to deeplink to the AppStore review section.

**Comment by kesha-antonov** [comment]
@oblador Hello! Please share example of deep link

**Comment by rpastorelle** [comment]
@oblador This won't build on versions of iOS < 10.3

```
/react-native-store-review/ios/RNStoreReview.m:2:9: 'StoreKit/SKStoreReviewController.h' file not found
```

**Comment by superandrew213** [comment]
@rpastorelle because it's only available for iOS >= 10.3. See [readme](https://github.com/oblador/react-native-store-review#react-native-store-review)

**Comment by jose920405** [comment]
IOS Documentation:

https://developer.apple.com/library/content/releasenotes/General/WhatsNewIniOS/Articles/iOS10_3.html

**Comment by pie6k** [comment]
Is it possible to build it with older version and enable it only on 10.3+?

**Comment by oblador** [comment]
@pie6k Yes that's possible.
