### ISSUE TITLE
Do not use this with a button

### ISSUE THREAD

**Issue by adambom** [oblador/react-native-store-review#14]
According to the [Apple Developer guidelines](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview)

> Because this method may or may not present an alert, it's not appropriate to call it in response to a button tap or other user action.

I would suggest including this in the README just so it's explicit.

This had me tapping my head for some time trying to figure out why it was failing to show in my app, even though it worked in development. Well, folks, if anyone else is having this issue, that's why. However, do not despair, there is a workaround:

```javascript
import {
  Linking,
  Platform,
} from 'react-native';


const APP_STORE_LINK = `itms-apps://itunes.apple.com/app/${IOS_APP_ID}?action=write-review`;
const PLAY_STORE_LINK = `market://details?id=${ANDROID_APP_ID}`;

const STORE_LINK = Platform.select({
  ios: APP_STORE_LINK,
  android: PLAY_STORE_LINK,
});

export default {
  requestReview: () => Linking.openURL(STORE_LINK),
};
```

**Comment by timwangdev** [comment]
There is a similar warning at https://github.com/KjellConnelly/react-native-rate#ios-specific

**Comment by oblador** [comment]
Hey, would you mind making a PR to improve the README?

**Comment by jnrepo** [comment]
@oblador if we reach Apple's limit for showing the store rating, will the flag `StoreReview.isAvailable` come back as true or false?

**Comment by oblador** [comment]
@jnrepo no, this flag is only wheter the API itself is available.

**Comment by jnrepo** [comment]
@oblador thank you for that quick reply!

**Comment by oblador** [comment]
Updated readme further and added example for button usage.
