### ISSUE TITLE
What happens when app is in Dev?

### ISSUE THREAD

**Issue by fhadsheikh** [oblador/react-native-store-review#15]
The app rating prompt comes up in dev. Just wondering what happens if I were to submit a review for the non production build.

Thanks

**Comment by oblador** [comment]
I'm not sure, assuming it wouldn't work – try! 😄

**Comment by Aldeee** [comment]
@fhadsheikh 
Sorry for the late feedback. You could follow the link and download the sample app https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews. Doing things exactly as described in the readme file, even on the simulator you will see the rating prompt window (partly functional I guess).

![image](https://user-images.githubusercontent.com/61188231/82220517-6a097380-9927-11ea-91e5-5682e776b3df.png)

**Comment by minafa96** [comment]
but I couldn't see the rating prompt in dev https://github.com/oblador/react-native-store-review/issues/51
