### ISSUE TITLE
React Native Bridge Warning (v0.51)

### ISSUE THREAD

**Issue by 505aaron** [oblador/react-native-store-review#16]
I am seeing the following warning in xcode when using the module.

> 2018-01-05 04:48:38.266 [warn][tid:main][RCTModuleData.mm:69] Module RNStoreReview requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

React Native Version: 0.51.0
iOS: 11.2
Device: iPhone 8 Simulator

**Comment by 505aaron** [comment]
I can look into fixing it if you would like.

**Comment by oblador** [comment]
This was fixed in [0.1.5](https://github.com/oblador/react-native-store-review/releases/tag/v0.1.5)
