### ISSUE TITLE
Sumitting does no working. Is it where I need to configure?

### ISSUE THREAD

**Issue by CarisL** [oblador/react-native-store-review#18]
Sumitting does no working. Is it where I need to configure?

This is my code, copy in  example

`  componentDidMount() {
    if (StoreReview.isAvailable) {
      StoreReview.requestReview();
    }
  }`

**Comment by Rajat421** [comment]
I am facing the same problem submit button is disabled

**Comment by CarisL** [comment]
you can read this link .
https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review

**Comment by nicolasdanelon** [comment]
I have the app in prod, not from test flight or itunes connect and I can't see the rates in itunes connect. Any idea why?

**Comment by marf** [comment]
Same problem here, I cannot submit my review

**Comment by nicolasdanelon** [comment]
Hi @Rajat421 and @marf I read the CarisL link and the Apple documentation I found this:

> When you call this method while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience. However, this method has no effect when you call it in an app that you distribute using TestFlight.

source: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview#discussion

thanks @CarisL for clarifying this issue with your link!

**Comment by marf** [comment]
Hello, the app in my case is in release mode, the dialog appears but the submit button does nothing.
