### ISSUE TITLE
simulator version works, release version not working

### ISSUE THREAD

**Issue by joe-lz** [oblador/react-native-store-review#19]
ios 12
"react-native": "0.57.0",
"react-native-store-review": "^0.1.5",

**Comment by joe-lz** [comment]
simulator shows prompt
appstore version did not show prompt
testflight also did not show prompt

**Comment by lolobosse** [comment]
Hey @jeodiong,

Did you find a solution or why was it not working?

**Comment by joe-lz** [comment]
@lolobosse only works for app on appstore, and 3 times in a year

**Comment by lolobosse** [comment]
@jeodiong Thanks a lot.

@oblador It might be useful to add following links to the doc: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews and this SO question (that's how I found out): https://stackoverflow.com/questions/46770549/skstorereviewcontroller-requestreview-popup-is-not-showing-in-testflight-build/47048474#47048474

**Comment by oblador** [comment]
@lolobosse Yep, would you mind making a PR?
