### ISSUE TITLE
Can display the prompt more than 3 times in a year

### ISSUE THREAD

**Issue by jonolock91** [oblador/react-native-store-review#2]
This might not be a bug... but I can show the review prompt over and over again, even when using `StoreReview.isAvailable`, according to the Apple docs it says `for up to three prompts in a 365-day period` - Do I need to manage this myself or should the library not allow me to call the method to show the prompt?

**Comment by aforty** [comment]
Is this in a development or testing environment? I believe in production (i.e. downloaded from the app store) Apple will limit this to 3 times a year on their end of the API.

**Comment by jonolock91** [comment]
This is during testing with the app set the release mode, so potentially it will be fine for production. I just wanted to check really.

**Comment by oblador** [comment]
@jonolock91 The `isAvailable` flag is just for the API itself being available (i.e. being on the right platform, version and properly linked). AFAIK whether or not the prompt will be displayed or not is a black box.
