### ISSUE TITLE
How I can check existence review for my app ?

### ISSUE THREAD

**Issue by NarekChang** [oblador/react-native-store-review#20]
How I can check existence review for my app? I can use with lib for that? I can't find tutorial's for solution.

**Comment by isaaclem** [comment]
I believe you can store a flag somewhere for that?

**Comment by buraksak35** [comment]
> I believe you can store a flag somewhere for that?

how do we handle if the user has voted at that moment or before ?

**Comment by isaaclem** [comment]
@buraksak35: You can store the flag using asyncstorage or redux.

**Comment by manakuro** [comment]
> You can store the flag using asyncstorage or redux.

That's nice but how would we know the user has submitted by using `StoreReview.requestReview()`? It doesn't seem like there is no callback for that. 

It'll be awesome if we have `onSubmit` callback like this.

```.js
StoreReview.requestReview(success => {
 if (success) {
   // submit succeed here and we can store flag
  AsyncStorage.setItem('isAlreadyRate', 'true')
 }
})
```

**Comment by oblador** [comment]
It's not possible with the existing APIs, there is a hack for iOS you can try it but it might break in the future: https://github.com/oblador/react-native-store-review/pull/37
