### ISSUE TITLE
Not working on latest version of React Native

### ISSUE THREAD

**Issue by mohanbhupathi** [oblador/react-native-store-review#23]

**Comment by oblador** [comment]
Did it stop working? What errors are you seeing?

**Comment by mohanbhupathi** [comment]
It worked fine when I implemented this in older version of RN, when i switch to RN-v0.58.3, StoreReview.isAvailable is being false. We use different bundle identifiers in prod. For test we use a different identifier and enterprise distribution. Does it have any dependency on bundle?

**Comment by oblador** [comment]
Yes it won't work in enterprise builds

**Comment by lunarraid** [comment]
I can confirm that this is broken on the latest react native. Calling it doesn't show any views, but prevents any further interaction with the app.

**Comment by yelkamel** [comment]
strange, it's work for me:

    "react-native-store-review": "^0.1.5",
    "react-native": "0.61.4",

**Comment by oblador** [comment]
I'm using this in production with latest 0.63 and I also updated the example project with this version. Open a new issue with reproduction steps if it persists.
