### ISSUE TITLE
RCTBridgeModule 'file now found' issues

### ISSUE THREAD

**Issue by abidulrmdn** [oblador/react-native-store-review#28]
#ISSUE 
I tried the 3 ways of linking the lib to ios but this doesnt seem to be working fine (beside andorid which works just fine).
Issue happening is shown below:
```
In file included from /Users/studocu/development/app/node_modules/react-native-store-review/ios/RNStoreReview.h:2:
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~

1 error generated.



** BUILD FAILED **
```

Some people suggesting changes in React-native folders and so on. Not sure how to make this work though!?

FYI:
react-native-cli: 2.0.1
react-native: 0.58.6
Xcode 10.2
react-native-store-review: 0.1.5

**Comment by abidulrmdn** [comment]
Only way I was able to make this work is by changing react-native/React/Base/RCTBridgeModule.h
and putting 
```
#import "RCTDefines.h"
```
instead of 
```
#import <React/RCTDefines.h>
```

but then I cannot append that to my project (nor this is a problem in react!)
Not sure why we use 2 different ways of importing and why the normal one doesn't work!

**Comment by vpontis** [comment]
@abdrmdn what option did you end up going with? I see you opened two issues that I ran into :)

**Comment by abidulrmdn** [comment]
@vpontis check the other similar repo (they're forked from eachother)
https://github.com/KjellConnelly/react-native-rate/pull/35
p.s: still no big final solution.

**Comment by tawanorg** [comment]
I have same issue

**Comment by patbenatar** [comment]
I was able to get it working by using the cocoapods approach instead of react-native link: https://github.com/oblador/react-native-store-review#using-cocoapods

**Comment by oblador** [comment]
This issue should not be applicable with autolinking anymore.
