### ISSUE TITLE
Leave a review - text is not visible...

### ISSUE THREAD

**Issue by patrickxkim** [oblador/react-native-store-review#32]
I have a strange behaviour.  Everything works fine, but when a user clicks to leave a review, the optional comment review section is all bg color when you type your review in.  The title section comes out fine with black text.  But the review section text is the same as bg color and you cant see what you are typing.  I tested it out in several devices and same issue... please help!  I even tried react-native-rate and same issue there...

**Comment by yarikpwnzer** [comment]
@patrickxkim same issue:
![Image from iOS](https://user-images.githubusercontent.com/5438263/68948136-e330de00-07bf-11ea-8010-2aeb1740b7c5.png)

**Comment by pabloluz** [comment]
@patrickxkim @yarikpwnzer Hey guys. This looks more like an iOS issue than something from this library. Are you still facing it?

**Comment by oblador** [comment]
Closing this as an OS/app bug, this library has no access to control any UI.
