### ISSUE TITLE
0.60+ autolinking instructions

### ISSUE THREAD

**Issue by jacobp100** [oblador/react-native-store-review#33]
I managed to get this working on 0.60 by `yarn add`ing it and `pod install` in the ios directory

I'm not sure if that's actually the right route, but if it is, it would be good to add this to the docs! Happy to submit a PR

**Comment by opeologist** [comment]
looks like the pod install route actually needs /ios at the end for it to work properly.  in the readme it talks about it, but the autolinking should definitely update to reflect the actual location so you don't have any manual steps!

readme ref: https://github.com/oblador/react-native-store-review#using-cocoapods

**Comment by nabilfreeman** [comment]
Hey, I also managed to autolink out of the box on RN 0.61 without needing to do any custom steps.

**Comment by peteroid** [comment]
My steps to get it working on 0.62

```
$ yarn add react-native-store-review
$ cd ios && pod install
```
