### ISSUE TITLE
App crashes when requesting for review

### ISSUE THREAD

**Issue by nascimentorafael** [oblador/react-native-store-review#4]
I am developing an app that uses this module to ask for a review. The thing is: the app is freezing after the alert appears.

I don't know if it helps, but I'm also having this on the console:

`
Required dispatch_sync to load constants for RNStoreReview. This may lead to deadlocks`

We could not catch any exceptions.

**Comment by oblador** [comment]
Hi, do you have any code to show how you're using it? Is this on device or in simulator? Does the Example project work for you?

**Comment by nascimentorafael** [comment]
The code I'm using is pretty like to the on you have in your readme file. We are importing the module and checking if the lib is available and then calling 'request review'.

We did some research and it seems like it does not crash once the app is live.

I'm closing this issue.

Thank you!
