### ISSUE TITLE
Wrong instruction in npm

### ISSUE THREAD

**Issue by mark-playco** [oblador/react-native-store-review#50]
Hey, you still have wrong instruction on the npm page
<img width="833" alt="Screenshot 2021-04-20 at 11 42 19" src="https://user-images.githubusercontent.com/79190772/115365952-8663ff00-a1cd-11eb-93d0-bf05da91a7b6.png">

It took some time to figure the problem out.

**Comment by pabloluz** [comment]
@mark-playco this seems to be fixed :)

**Comment by mirocosic** [comment]
> @mark-playco this seems to be fixed :)

I can still see this in npm.

**Comment by oblador** [comment]
Should have been fixed for quite some time now :-)
