### ISSUE TITLE
can we put custom text?

### ISSUE THREAD

**Issue by jose920405** [oblador/react-native-store-review#6]
![captura de pantalla 2017-08-31 a la s 11 28 49 a m](https://user-images.githubusercontent.com/12536184/29934107-93940936-8e3f-11e7-8a1e-a58071c14196.png)

i wan't change that text.. its possible?

**Comment by oblador** [comment]
Unfortunately not, the iOS API don't expose it.

**Comment by jose920405** [comment]
hi @oblador , thanks for answer, can you help me find out what part of the documentation says that?

**Comment by oblador** [comment]
The function takes no arguments at all :-)

**Comment by oblador** [comment]
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

**Comment by jose920405** [comment]
Thanks
