### ISSUE TITLE
Do I need to know that the user will see it for the first time?

### ISSUE THREAD

**Issue by bloggerklik** [oblador/react-native-store-review#67]
Hi, do I need to know that the user will see it for the first time?

After a certain step in the my application StoreReview.requestReview(); I'm thinking of running it. But I don't know the user's status.

StoreReview.requestReview(); should it be run once? Will it still show if it was previously shown to the user or if the user has commented before?

Thanks.

**Comment by oblador** [comment]
The docs state:
>The intention of this API is to ask the user to rate the app as a part of the user journey, typically as the user completes a task. Since it's not possible to know if a dialog will be shown or not you should not call it as a result of tapping a button, but rather as a side effect of an event happening in the app.

Run it as many times you like.
