### ISSUE TITLE
[Android] StoreReview.requestReview() is not working

### ISSUE THREAD

**Issue by federicomiralles** [oblador/react-native-store-review#76]
To replicate this issue run the Example included in the repo...
As you can see on the attached video the lib works properly on iOS but it neither works on Android nor throws any error pinpointing the possible reason of the failure:

https://user-images.githubusercontent.com/53195495/213585093-1ec39a9f-0a73-4e86-8074-daf17aafeedb.mov

Any idea @oblador?

**Comment by ahlbet** [comment]
hey @federicomiralles ! We were running into this issue as well on Android. After looking over https://developer.android.com/guide/playcore/in-app-review/kotlin-java and this package's Android bridge code, we realized that react-native-store-review is missing the code that is responsible for launching the review:

```
Task<Void> flow = manager.launchReviewFlow(activity, reviewInfo);
```

We ended up creating our own Android module that includes that code for handling reviews. If I find some time, I'll create a PR for this package. Let me know if you have any questions on it.

**Comment by metinaltinbas** [comment]
I also experience this issue. @oblador

**Comment by leechoohyoung** [comment]
same here.

**Comment by robinshin** [comment]
same here

**Comment by marcshilling** [comment]
@ahlbet is right - it doesn't seem like the Android code is completing the full process. You can see some other rate libraries doing this:
https://github.com/MinaSamir11/react-native-in-app-review/blob/master/android/src/main/java/com/ibits/react_native_in_app_review/AppReviewModule.java#L67

**Comment by drskyhook** [comment]
would patch package work if we just add this line?

--where should it be added?

**Comment by Barney4242** [comment]
same issue
