### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by lex111** [oblador/react-native-store-review#8]

**Comment by oblador** [comment]
Does the Play store provide a similar API?

**Comment by lex111** [comment]
Most likely not, but if you do something similar?

**Comment by oblador** [comment]
What did you have in mind? Don't have very large plans for this library, just be a wrapper of the native APIs.

**Comment by lex111** [comment]
Ok, I just thought, create for example an Android modal window, similar on iOS, but open Google Play to rate the application.

**Comment by superandrew213** [comment]
@lex111 you can use this https://github.com/jlyman/react-native-rating-requestor

**Comment by karltaylor** [comment]
@superandrew213 would be good to not have to use two different modules but hey ho.

**Comment by Noitidart** [comment]
Android Play store support would be so ultra ultra cool

**Comment by carloscuesta** [comment]
PlayStore allows in-app ratings?

**Comment by lolobosse** [comment]
@carloscuesta No: https://stackoverflow.com/a/11270668/2545832

**Comment by pabloluz** [comment]
> PlayStore allows in-app ratings?

They just started (around two months ago) to test that feature. More info here: https://www.androidpolice.com/2019/10/25/play-store-tests-include-new-in-app-review-dialogs-and-a-dedicated-reviews-section/

**Comment by frenberg** [comment]
Its been released now, since about a week or so. Should be possible to add wrap the android implementation too https://developer.android.com/guide/playcore/in-app-review

**Comment by geraintwhite** [comment]
Looks like there is another module that provides the API for both platforms https://github.com/MinaSamir11/react-native-in-app-review

**Comment by oblador** [comment]
Added in #38 and available in [0.2.0](https://github.com/oblador/react-native-store-review/releases/tag/v0.2.0)
