### ISSUE TITLE
Submit button is disabled.

### ISSUE THREAD

**Issue by hayr-hotoca** [oblador/react-native-store-review#87]
On dev and prod(not the version downloaded from App Store), the submit button is disable so I can't complete the review.
![Screenshot 2023-09-29 at 23 03 30](https://github.com/oblador/react-native-store-review/assets/21136244/9af05cb3-df58-484b-bc54-9a0c62769652)

**Comment by oblador** [comment]
You can only rate apps in the App Store, this is a limitation/behavior of the underlying API not a bug in this library.
