### ISSUE TITLE
[Question] is there a way to know if rate dialog was shown to user or not? Or to catch errors while requesting for review?

### ISSUE THREAD

**Issue by Ggayane** [oblador/react-native-store-review#92]
is there a way to know if rate dialog was shown to user or not? Or to catch errors while requesting for review?

**Comment by Dmitry-GH** [comment]
@Ggayane from the ReadMe, right at the beginning of the Usage section:

> The intention of this API is to ask the user to rate the app as a part of the user journey, typically as the user completes a task. **Since it's not possible to know if a dialog will be shown or not you should not call it as a result of tapping a button**, but rather as a side effect of an event happening in the app.

So no, we can't determine does dialog was shown, etc.
